### ISSUE TITLE
Rendering of timeslotsperhour compared to hours

### ISSUE THREAD

**Issue by DarrenGoddard** [FourjsGenero/wc_weekcalendar#2]
There seems to be an issue with how the Calendar hours are rendered against the actual hourly display on the left hand side of the calendar.  This does not occur when looking at the source for the web component and running the demos.  Is this an issue with the web component interface in Genero?

I've also tried adjusting the timeslotheight but it doesn't seem to be able to agree with the height of the hour display rows on the left regardless of what is done.

Otherwise, a great WC implementation and great example too.

Any ideas?

**Comment by fourjs-cg** [comment]
Thank you, the height issue should be fixed now. It was a computation problem in jquery.weekcalendar.js line 867. If writing your own calendar based on this same web component, be careful to not allow options.timeslotHeight * options.timeslotsPerHour < 11
